/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as TthRouteImport } from './routes/tth'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TravelSheetsRouteImport } from './routes/travel.sheets'

const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const TthRoute = TthRouteImport.update({
  id: '/tth',
  path: '/tth',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelSheetsRoute = TravelSheetsRouteImport.update({
  id: '/travel/sheets',
  path: '/travel/sheets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/tth': typeof TthRoute
  '/warehouse': typeof WarehouseRoute
  '/travel/sheets': typeof TravelSheetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/tth': typeof TthRoute
  '/warehouse': typeof WarehouseRoute
  '/travel/sheets': typeof TravelSheetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/tth': typeof TthRoute
  '/warehouse': typeof WarehouseRoute
  '/travel/sheets': typeof TravelSheetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reports' | '/tth' | '/warehouse' | '/travel/sheets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reports' | '/tth' | '/warehouse' | '/travel/sheets'
  id: '__root__' | '/' | '/reports' | '/tth' | '/warehouse' | '/travel/sheets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsRoute: typeof ReportsRoute
  TthRoute: typeof TthRoute
  WarehouseRoute: typeof WarehouseRoute
  TravelSheetsRoute: typeof TravelSheetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tth': {
      id: '/tth'
      path: '/tth'
      fullPath: '/tth'
      preLoaderRoute: typeof TthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel/sheets': {
      id: '/travel/sheets'
      path: '/travel/sheets'
      fullPath: '/travel/sheets'
      preLoaderRoute: typeof TravelSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsRoute: ReportsRoute,
  TthRoute: TthRoute,
  WarehouseRoute: WarehouseRoute,
  TravelSheetsRoute: TravelSheetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
