/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaybillRouteImport } from './routes/waybill'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as TthRouteImport } from './routes/tth'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as IndexRouteImport } from './routes/index'

const WaybillRoute = WaybillRouteImport.update({
  id: '/waybill',
  path: '/waybill',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const TthRoute = TthRouteImport.update({
  id: '/tth',
  path: '/tth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/reset': typeof ResetRoute
  '/tth': typeof TthRoute
  '/warehouse': typeof WarehouseRoute
  '/waybill': typeof WaybillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/reset': typeof ResetRoute
  '/tth': typeof TthRoute
  '/warehouse': typeof WarehouseRoute
  '/waybill': typeof WaybillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/reset': typeof ResetRoute
  '/tth': typeof TthRoute
  '/warehouse': typeof WarehouseRoute
  '/waybill': typeof WaybillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reports' | '/reset' | '/tth' | '/warehouse' | '/waybill'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reports' | '/reset' | '/tth' | '/warehouse' | '/waybill'
  id:
    | '__root__'
    | '/'
    | '/reports'
    | '/reset'
    | '/tth'
    | '/warehouse'
    | '/waybill'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsRoute: typeof ReportsRoute
  ResetRoute: typeof ResetRoute
  TthRoute: typeof TthRoute
  WarehouseRoute: typeof WarehouseRoute
  WaybillRoute: typeof WaybillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waybill': {
      id: '/waybill'
      path: '/waybill'
      fullPath: '/waybill'
      preLoaderRoute: typeof WaybillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tth': {
      id: '/tth'
      path: '/tth'
      fullPath: '/tth'
      preLoaderRoute: typeof TthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsRoute: ReportsRoute,
  ResetRoute: ResetRoute,
  TthRoute: TthRoute,
  WarehouseRoute: WarehouseRoute,
  WaybillRoute: WaybillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
